### ISSUE TITLE
Create API call to Spotify to DELETE all songs from master playlist

### ISSUE THREAD

**Issue by m4ndycheung** [m4ndycheung/cyf-stay-tuned-radio#25]

**Comment by ManSangSin** [comment]
issue: the uri of each track we want to remove is required to be sent in the fetch API to delete the songs from the playlist

we will need a function to read the current spotify playlist and return the uri of each track inside the playlist

uri example: spotify:track:4iV5W9uYEdYUVa79Axb7Rh [spotify:datatype:id]

**Comment by m4ndycheung** [comment]
> function to read the current spotify playlist and return the uri of each track inside the playlist
> 
> uri example: spotify:track:4iV5W9uYEdYUVa79Axb7Rh [spotify:datatype:id]

What did you decide to do with this? Would you like to make that function to read the current Spotify playlist it's own ticket?

**Comment by ManSangSin** [comment]
> > function to read the current spotify playlist and return the uri of each track inside the playlist
> > uri example: spotify:track:4iV5W9uYEdYUVa79Axb7Rh [spotify:datatype:id]
> 
> What did you decide to do with this? Would you like to make that function to read the current Spotify playlist it's own ticket?

Hi, I just made a PR for both the reading and deleting of the tracks. I've separated them in different modules so I can split the PR if its too large
