### ISSUE TITLE
Create table on database to store refresh token

### ISSUE THREAD

**Issue by m4ndycheung** [m4ndycheung/cyf-stay-tuned-radio#31]

**Comment by m4ndycheung** [comment]
![Image](https://github.com/m4ndycheung/cyf-stay-tuned-radio/assets/109825538/06fa9040-809f-4115-8aae-304a1007e660)

Added a table to the DB. It's got ID and refresh_token columns. 
Expiry didn't seem to matter seeing as it's infinite. Do we need anymore columns?

**Comment by christina-mifsud** [comment]
LGTM - using table and it's all working as expected!
