### ISSUE TITLE
Create Postgres DB - BE - UserStory2 🐑

### ISSUE THREAD

**Issue by m4ndycheung** [m4ndycheung/cyf-stay-tuned-radio#5]
To Dos:
1. Create a db
2. Create a table to hold the songs
3. Columns: song id, song name, artist, slack username, genre
4. Insert 10 songs into table

fOR Reviewer: Check DB on dbeaver, a second eye on the data we're storing is okay

**Comment by christina-mifsud** [comment]
Postgres DB created and deployed on Render.
A table was created and 10 random songs were added.

![Image](https://github.com/m4ndycheung/cyf-stay-tuned-radio/assets/102205880/f05a7f4e-f536-49c1-bc0e-a7eb2978e431)

![Image](https://github.com/m4ndycheung/cyf-stay-tuned-radio/assets/102205880/6f157857-78e9-4010-b7ac-006e4e555ca4)

**Comment by munozirianni1988** [comment]
Check the data and it looks fine to me :)
